import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">HomeDashboard</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/scheduledashboard">ScheduleDashboard</Link>
        </li>
        <li>
          <Link to="/tasksdashboard">TasksDashboard</Link>
        </li>
        <li>
          <Link to="/messagesdashboard">MessagesDashboard</Link>
        </li>
        <li>
          <Link to="/meetingsdashboard">MeetingsDashboard</Link>
        </li>
        <li>
          <Link to="/profiledashboard">ProfileDashboard</Link>
        </li>
        <li>
          <Link to="/homedashboardnotification">HomeDashboardNotification</Link>
        </li>
        <li>
          <Link to="/tasksdashboardopenedtask">TasksDashboardOpenedTask</Link>
        </li>
        <li>
          <Link to="/inmeetingdashboard">InMeetingDashboard</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
